# "`-''-/").___..--''"`-._
#  (`6_ 6  )   `-.  (     ).`-.__.`)   WE ARE ...
#  (_Y_.)'  ._   )  `._ `. ``-..-'    PENN STATE!
#    _ ..`--'_..-_/  /--'_.' ,'
#  (il),-''  (li),'  ((!.-'
# 
# Author: Weiming Hu <weiming@psu.edu>
#         Geoinformatics and Earth Observation Laboratory (http://geolab.psu.edu)
#         Department of Geography and Institute for CyberScience
#         The Pennsylvania State University
#

#' RAnEn::convertToAdvance
#' 
#' @description 
#' RAnEn::convertToAdvance converts a configuration to an advanced one.
#' 
#' @author Weiming Hu \email{weiming@@psu.edu}
#' 
#' @param configuration A configuration object generated by the function
#' \code{\link{generateConfiguration}}.
#' 
#' @return An advanced configuration.
#' 
#' @useDynLib RAnEn
#' 
#' @export
convertToAdvance <- function(config) {
  if (config$advanced) {
    return (config)
  }
  
  config$advanced <- T
  
  if (all(c("forecasts", "forecast_times") %in% names(config))) {
    config$test_forecasts <- config$forecasts
    config$test_times <- config$forecast_times
    config$search_forecasts <- config$forecasts
    config$search_times <- config$forecast_times
    config$test_stations_classifier <- config$stations_classifier
    config$search_stations_classifier <- config$stations_classifier
    
    delete.index <- which("forecasts" == names(config))
    delete.index <- c(delete.index, which("forecast_times" == names(config)))
    delete.index <- c(delete.index, which("stations_classifier" == names(config)))
    config <- config[-delete.index]
  } else {
    stop("Error: Possibly missing forecasts and/or forecasts_times.")
  }
  
  if (config$mode == 'extendedSearch') {
    
    if (all(c("forecast_stations_x", "forecast_stations_y") %in% names(config))) {
      config$test_stations_x <- config$forecast_stations_x
      config$test_stations_y <- config$forecast_stations_y
      
      config$search_stations_x <- config$forecast_stations_x
      config$search_stations_y <- config$forecast_stations_y
      
      delete.index <- which("forecast_stations_x" == names(config))
      delete.index <- c(delete.index, which("forecast_stations_y" == names(config)))
      config <- config[-delete.index]
    } else {
      stop("Error: Possibly missing forecast_stations_x and/or forecast_stations_y")
    }
  }
  
  class(config) <- 'Configuration'
  
  return(config)
}
