# "`-''-/").___..--''"`-._
#  (`6_ 6  )   `-.  (     ).`-.__.`)   WE ARE ...
#  (_Y_.)'  ._   )  `._ `. ``-..-'    PENN STATE!
#    _ ..`--'_..-_/  /--'_.' ,'
#  (il),-''  (li),'  ((!.-'
# 
# Author: Weiming Hu <weiming@psu.edu>
#         Geoinformatics and Earth Observation Laboratory (http://geolab.psu.edu)
#         Department of Geography and Institute for CyberScience
#         The Pennsylvania State University
#

#' RAnEn::formatConfiguration
#' 
#' RAnEn::formatConfiguration formats configuration memebers.
#' 
#' Sometimes, a configuration member can be automatically formatted. For example,
#' for time variables, R has a POSIXct time but it is represented as numerics in
#' RAnEn. So this can be automicatially converted internally. This function
#' checks for those possibility to format configuration variables.
#' 
#' @author Weiming Hu \email{weiming@@psu.edu}
#' 
#' @param config A configuration object generated by the function
#' \code{\link{generatedConfiguration}}.
#' @param verbose Whether to print progress information.
#' 
#' @return The formatted configuration.
#' 
#' @export
formatConfiguration <- function(config, verbose = T) {
  if (class(config) != 'Configuration')
    stop("Class is not Configuration.")
  
  config$flts <- as.numeric(config$flts)
  
  for (name in c('test_times', 'search_times',
                 'forecast_times', 'observation_times',
                 'test_times_compare', 'search_times_compare')) {
    if (name %in% names(config)) {
      if (inherits(config[[name]], 'POSIXt')) {
        config[[name]] <- as.numeric(config[[name]])
      } else if (is.array(config[[name]])) {
        config[[name]] <- as.vector(config[[name]])
      } 
    }
  }
  
  for (name in c('test_stations_x', 'test_stations_y',
                 'search_stations_x', 'search_stations_y',
                 'forecast_stations_x', 'forecast_stations_y')) {
    if (name %in% names(config)) {
      config[[name]] <- as.vector(config[[name]])
    }
  }
  
  if (length(config$weights) == 0) {
      if (config$advanced) {
        config$weights <- rep(1, times = dim(config[['test_forecasts']])[1])
      } else {
        config$weights <- rep(1, times = dim(config[['forecasts']])[1])
      }
  }
  
  return(config)
}
