# "`-''-/").___..--''"`-._
#  (`6_ 6  )   `-.  (     ).`-.__.`)   WE ARE ...
#  (_Y_.)'  ._   )  `._ `. ``-..-'    PENN STATE!
#    _ ..`--'_..-_/  /--'_.' ,'
#  (il),-''  (li),'  ((!.-'
# 
# Author: Weiming Hu <weiming@psu.edu>
#         Geoinformatics and Earth Observation Laboratory (http://geolab.psu.edu)
#         Department of Geography and Institute for CyberScience
#         The Pennsylvania State University
#

#' RAnEn::generateAnalogs
#' 
#' RAnEn::generateAnalogs returns the generated analog ensembles with either 
#' ensemble values and/or ensemble index. It can also return a number of 
#' auxiliary information, for example, similarity metrics and search stations.
#' These can be customized in the configuration object generated by the
#' function \code{\link{generateConfiguration}}.
#' 
#' @author Weiming Hu \email{weiming@@psu.edu}
#' 
#' @param configuration A configuration object generated by the function
#' \code{\link{generateConfiguration}}. As a good practice, the configuration object
#' should be validated by the function \code{\link{validateConfiguration}} before
#' usage.
#' 
#' @return An AnEn list with customized members. The list member **analogs**
#' is a 5-dimensional array that contains values and indices of ensemble
#' members from the variable observations. The dimensions are 
#' **analogs\[test stations, test days, FLT, members, ...\]**
#' where FLT stands for forecast lead time. The size of the fifth dimension
#' is 3, storing the value \[,,,,1\], station index \[,,,,2\], and day index
#' \[,,,,3\]. The list member **similarity** stores the similarity metrics.
#' The dimension indication is the same with the member analogs. The list
#' member **searchStations** stores the search station index. The list member
#' **mapping** stores the mapping mechanism from the time and the flt in
#' forecasts to the time in observations. For negative values in the member time
#' index column for analogs and similarity, please refer to
#' [AnEn::selectAnalogs](https://weiming-hu.github.io/AnalogsEnsemble/CXX/class_an_en.html#a8e2b88cda5cc9fce8ea4703a3236719c) 
#' and [AnEn::computeSimilarity](https://weiming-hu.github.io/AnalogsEnsemble/CXX/class_an_en.html#ad032b4a80d86c6c31ef26a3eb381cb5d).
#' 
#' @import Rcpp BH
#' 
#' @useDynLib RAnEn
#' 
#' @md
#' @export
generateAnalogs <- function(configuration) {
  
  valid <- validateConfiguration(configuration, configuration$verbose)
  if (!valid) return(valid)
  
  configuration <- convertToAdvance(configuration)
  
  configuration$observation_id = configuration$observation_id - 1
  
  if (configuration$mode == 'independentSearch') {
    
    # Create default values
    if ("test_stations_x" %in% names(configuration) &&
        "test_stations_y" %in% names(configuration) &&
        "search_stations_x" %in% names(configuration) &&
        "search_stations_y" %in% names(configuration)) {
      test_forecasts_station_x <- configuration$test_stations_x
      test_forecasts_station_y <- configuration$test_stations_y
      search_forecasts_station_x <- configuration$search_stations_x
      search_forecasts_station_y <- configuration$search_stations_y
    } else {
      test_forecasts_station_x <- vector(mode = 'numeric', length = 0)
      test_forecasts_station_y <- vector(mode = 'numeric', length = 0)
      search_forecasts_station_x <- vector(mode = 'numeric', length = 0)
      search_forecasts_station_y <- vector(mode = 'numeric', length = 0)
    }
    
    search_extension <- F
    max_num_search_stations <- 0
    distance <- 0
    num_nearest_stations <- 0
    
    AnEn <- .generateAnalogs(
      configuration$test_forecasts, dim(configuration$test_forecasts),
      test_forecasts_station_x,
      test_forecasts_station_y,
      configuration$test_times,
      configuration$search_forecasts, dim(configuration$search_forecasts),
      search_forecasts_station_x,
      search_forecasts_station_y,
      configuration$search_times,
      configuration$flts,
      configuration$search_observations, dim(configuration$search_observations),
      configuration$observation_times,
      configuration$weights,
      configuration$num_members,
      configuration$observation_id, configuration$quick,
      configuration$circulars, search_extension,
      configuration$extend_observations,
      configuration$preserve_similarity,
      configuration$preserve_mapping,
      configuration$preserve_search_stations,
      configuration$preserve_std,
      max_num_search_stations, distance,
      num_nearest_stations, configuration$time_match_mode,
      configuration$max_par_nan, configuration$max_flt_nan,
      configuration$test_times_compare,
      configuration$search_times_compare,
      configuration$operational,
      configuration$max_num_sims,
      configuration$verbose)
    
  } else if (configuration$mode == 'extendedSearch') {
    # Create default values
    search_extension <- T
    
    AnEn <- .generateAnalogs(
      configuration$test_forecasts, dim(configuration$test_forecasts),
      configuration$test_stations_x,
      configuration$test_stations_y,
      configuration$test_times,
      configuration$search_forecasts, dim(configuration$search_forecasts),
      configuration$search_stations_x,
      configuration$search_stations_y,
      configuration$search_times,
      configuration$flts,
      configuration$search_observations, dim(configuration$search_observations),
      configuration$observation_times,
      configuration$weights,
      configuration$num_members,
      configuration$observation_id, configuration$quick,
      configuration$circulars, search_extension,
      configuration$extend_observations,
      configuration$preserve_similarity,
      configuration$preserve_mapping,
      configuration$preserve_search_stations,
      configuration$preserve_std,
      configuration$max_num_search_stations,
      configuration$distance,
      configuration$num_nearest,
      configuration$time_match_mode,
      configuration$max_par_nan,
      configuration$max_flt_nan,
      configuration$test_times_compare,
      configuration$search_times_compare,
      configuration$operational,
      configuration$max_num_sims,
      configuration$verbose)
    
  } else {
    stop('Unknown configuration mode!')
  }
  
  # Because similarity matrix was stored in row-major in C++ and the R object will be column-major.
  # So change the order of dimensions to make it conform with other objects.
  #
  if (configuration$preserve_similarity) {
    AnEn$similarity <- aperm(AnEn$similarity, length(dim(AnEn$similarity)):1)

    ori <- as.vector(AnEn$similarity[, , , , 3])
    ori[which(ori >= 0)] <- ori[which(ori >= 0)] + 1
    AnEn$similarity[, , , , 3] <- ori

    AnEn$similarity[, , , , 2] <- AnEn$similarity[, , , , 2, drop = F] + 1
  }

  if (configuration$preserve_search_stations) {
    AnEn$searchStations <- AnEn$searchStations + 1
  }

  # Convert station index from C counting to R counting
  AnEn$analogs[, , , , 2] <- AnEn$analogs[, , , , 2, drop = F] + 1

  # Convert time index from C to R if the index is non-negative
  ori <- as.vector(AnEn$analogs[, , , , 3])
  ori[which(ori >= 0)] <- ori[which(ori >= 0)] + 1
  AnEn$analogs[, , , , 3] <- ori

  if (configuration$preserve_mapping) AnEn$mapping <- AnEn$mapping + 1

  if (configuration$verbose >= 3)  cat("Done!\n")
  
  return(AnEn)
}
