# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
checkOpenMP <- function() {
    .Call(`_RAnEn_checkOpenMP`)
}

#' @name Config
#' @title Exposed C++ Class Config
#' @description Analog generation can be fine-tuned with configuration. This
#' class provides all the tunable parameters for analog generation. You can
#' type `RAnEn::Config` in the R console to see the description for each parameter.
#' To create an object of Config, you can type `config <- new(Config)`, and then 
#' you can directly modify the members, e.g. `config$num_analogs <- 10`. To see
#' the full list of tunable parameters, you can type `config` after you have 
#' created an object. It will print all the parameters.
#' @md
#' @export
NULL

#' RAnEn::generateAnalogs
#' 
#' RAnEn::generateAnalogs generates analog ensemble.
#' 
#' @param sx_forecasts Forecasts. You can generate this by typing
#' `forecasts <- generateForecastsTemplate()`.
#' @param sx_observations Observations. You can generate this by typing
#' `observations <- generateObservationsTemplate()`
#' @param sx_test_times Test times
#' @param sx_search_times Search times
#' @param sx_config A Config. You can generate this by typing `config <- new(Config)`
#' @param sx_algorithm `IS` for independent search or `SSE` for search
#' space extension
#' @return A list of results with class AnEn. You can type `print(AnEn)`
#' to see a summary.
#' 
#' @md
#' @export
generateAnalogs.default <- function(sx_forecasts, sx_observations, sx_test_times, sx_search_times, sx_config = NULL, sx_algorithm = NULL) {
    .Call(`_RAnEn_generateAnalogs`, sx_forecasts, sx_observations, sx_test_times, sx_search_times, sx_config, sx_algorithm)
}

#' RAnEn::generateSearchStations
#' 
#' RAnEn::generateSearchStations calculates the nearest coordinates for all input coordinates.
#' 
#' @param sx_xs X coordinates
#' @param sx_ys Y coordinates
#' @param num_neighbors The number of neighbors to find
#' @param distance The distance threshold when finding nearest neighbors
#' @return A matrix for nearest search station index. Each row is a set of search station index
#' 
#' @md
#' @export
generateSearchStations <- function(sx_xs, sx_ys, num_neighbors, sx_distance = NULL) {
    .Call(`_RAnEn_generateSearchStations`, sx_xs, sx_ys, num_neighbors, sx_distance)
}

#' RAnEn::generateTimeMapping
#' 
#' RAnEn::generateTimeMapping generates the index mapping table from foreacst times and lead times
#' to observation times.
#' 
#' @param sx_fcst_times forecast times
#' @param sx_fcst_flts forecast lead times
#' @param sx_obs_times observation times
#' @return A matrix with rows being forecast times and columns being lead times, the cell
#' values are the index to the corresponding observation times.
#' 
#' @md
#' @export
generateTimeMapping <- function(sx_fcst_times, sx_fcst_flts, sx_obs_times) {
    .Call(`_RAnEn_generateTimeMapping`, sx_fcst_times, sx_fcst_flts, sx_obs_times)
}

