# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.checkOpenMP <- function() {
    .Call('_RAnEn_checkOpenMP', PACKAGE = 'RAnEn')
}

.generateAnEnIS <- function(R_config) {
    .Call('_RAnEn_computeAnEnIS', PACKAGE = 'RAnEn', R_config)
}

