# "`-''-/").___..--''"`-._
#  (`6_ 6  )   `-.  (     ).`-.__.`)   WE ARE ...
#  (_Y_.)'  ._   )  `._ `. ``-..-'    PENN STATE!
#    _ ..`--'_..-_/  /--'_.' ,'
#  (il),-''  (li),'  ((!.-'
# 
# Author: Weiming Hu <weiming@psu.edu>
#         Geoinformatics and Earth Observation Laboratory (http://geolab.psu.edu)
#         Department of Geography and Institute for CyberScience
#         The Pennsylvania State University
#

#' RAnEn::readConfig
#' 
#' RAnEn::readConfig reads a config file, usually generated by RAnEn::writeConfig
#' 
#' @author Weiming Hu \email{weiming@@psu.edu}
#' @param config.file The full path to the configuration file (.cfg)
#' @param replace.dash A single character to replace the dash in configuration names for. This can be set to `NULL`
#' if no replacement is desired.
#' @return A list
#' @md
#' @export
readConfig <- function (config.file, replace.dash = '_') {
  
  check.package('stringr')
  stopifnot(file.exists(config.file))
  
  # Read all lines from the file
  con <- file(config.file, "r")
  lines <- readLines(con = con)
  close(con)
  
  # Remove commented lines
  to.be.removed <- grep("(^#.*)|(^$)", lines)
  if (length(to.be.removed) != 0) {
    lines <- lines[-to.be.removed]
  }
  
  config <- list()
  
  # Parse lines
  for (line in lines) {
    
    # Split a line with space
    parts <- strsplit(line, "=")[[1]]
    
    if (length(parts) != 2) {
      stop('Some lines have multiple equal signs which is not allowed!')
    }
    
    # Remove spaces
    left <- stringr::str_replace(parts[1], ' +', '')
    right <- stringr::str_replace(parts[2], '^ +', '')
    
    # Replace dashes in the left
    if (!is.null(replace.dash)) {
      left <- stringr::str_replace_all(left, '-', replace.dash)
    }
    
    if (left %in% names(config)) {
      config[[left]] <- c(config[[left]], right)
    } else {
      config[[left]] <- right
    }
  }
  
  return(config)
}
