# "`-''-/").___..--''"`-._
#  (`6_ 6  )   `-.  (     ).`-.__.`)   WE ARE ...
#  (_Y_.)'  ._   )  `._ `. ``-..-'    PENN STATE!
#    _ ..`--'_..-_/  /--'_.' ,'
#  (il),-''  (li),'  ((!.-'
# 
# Author: Weiming Hu <weiming@psu.edu>
#         Geoinformatics and Earth Observation Laboratory (http://geolab.psu.edu)
#         Department of Geography and Institute for CyberScience
#         The Pennsylvania State University
#

#' RAnEn::readConfig
#' 
#' RAnEn::readConfig reads a config file, usually generated by RAnEn::writeConfig
#' 
#' @author Weiming Hu \email{weiming@@psu.edu}
#' @param config.file The full path to the configuration file (.cfg)
#' @return A config
#' @export
readConfig <- function(config.file) {
  stopifnot(file.exists(config.file))
  
  # Read file content as lines
  con <- file(config.file, 'r')
  lines <- readLines(con = con)
  close(con)
  
  # Remove comment lines and empty lines
  to.be.removed <- grep('(^#.*)|(^$)', lines)
  if (length(to.be.removed) != 0) {
    lines <- lines[-to.be.removed]
  }
  
  config <- new(Config)
  pairs <- config$getNames()
  
  for (line in lines) {
    parts <- strsplit(line, ' ')[[1]]
    
    key <- parts[1]
    value <- as.numeric(parts[3])
    
    if (key == pairs$`_WEIGHTS`) {
      config[[key]] <- c(config[[key]], value)
    } else if (key == pairs$`_OBS_ID`) {
      config[[key]] <- value + 1
    } else if (key == pairs$`_DISTANCE`) {
      if (value == -1) config[[key]] <- NaN
    } else {
      config[[key]] <- value
    }
  }
  
  return(config)
}
