fortran: false
env:
    global:
        - CODECOV_TOKEN=11fbe283-94bd-4eca-88d0-a3083178cf25
matrix:
    include:
        -
            os: linux
            language: cpp
            addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [g++-4.9, libnetcdf-dev, libnetcdf-c++4-dev, libcppunit-dev]}}
            env: ['MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"', 'ENVIRONMENT_LANGUAGE="c++"', 'INSTALL_ECCODES="YES"']
        -
            os: linux
            language: cpp
            addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [g++-5, libnetcdf-dev, libnetcdf-c++4-dev, libcppunit-dev]}}
            env: ['MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"', 'ENVIRONMENT_LANGUAGE="c++"', 'INSTALL_ECCODES="YES"']
        -
            os: linux
            language: cpp
            addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [g++-6, libnetcdf-dev, libnetcdf-c++4-dev, libcppunit-dev]}}
            env: ['MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"', 'ENVIRONMENT_LANGUAGE="c++"', 'INSTALL_ECCODES="YES"']
        -
            os: linux
            language: cpp
            addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [g++-7, libnetcdf-dev, libnetcdf-c++4-dev, libcppunit-dev]}}
            env: ['MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"', 'ENVIRONMENT_LANGUAGE="c++"', 'INSTALL_ECCODES="YES"']
        -
            os: linux
            language: cpp
            addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [g++-8, libnetcdf-dev, libnetcdf-c++4-dev, libcppunit-dev]}}
            env: ['MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"', 'ENVIRONMENT_LANGUAGE="c++"', 'INSTALL_ECCODES="YES"']
        -
            os: osx
            language: cpp
            env: ['MATRIX_EVAL="brew install eccodes cppunit"', 'ENVIRONMENT_LANGUAGE="c++"']
        -
            os: linux
            language: r
            cache: Rcpp
            addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [g++-4.9]}}
            env: ['ENVIRONMENT_LANGUAGE="r"']
        -
            os: osx
            language: r
            cache: Rcpp
            env: ['ENVIRONMENT_LANGUAGE="r"']
before_install:
    - set -e
    - cmake --version
    - eval "${MATRIX_EVAL}"
    - if [[ "$ENVIRONMENT_LANGUAGE" == "r" ]]; then R -e "install.packages(c('abind', 'Rcpp', 'BH', 'ncdf4'))";fi
    - if [[ "$INSTALL_ECCODES" == "YES" ]]; then ./CAnEnIO/cmake/install_eccodes.sh;fi
install:
    - if [[ "$ENVIRONMENT_LANGUAGE" == "r" ]]; then R CMD INSTALL RAnalogs/releases/RAnEn_latest.tar.gz; fi
script:
    - if [[ "$ENVIRONMENT_LANGUAGE" == "c++" ]]; then mkdir build; cd build; CC=$CC CXX=$CXX cmake -DCMAKE_CXX_FLAGS="-coverage" -DCMAKE_PREFIX_PATH=~/eccodes ..; make -j16; fi
after_success:
    - if [[ "$ENVIRONMENT_LANGUAGE" == "c++" ]]; then make test; fi
    - if [[ "$ENVIRONMENT_LANGUAGE" == "r" ]]; then cd RAnalogs/tests; Rscript test_all.R; fi
    - bash <(curl -s https://codecov.io/bash)

