env:
   global:
    - CODECOV_TOKEN=11fbe283-94bd-4eca-88d0-a3083178cf25

matrix:
   include:
     - os: linux
       language: cpp
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-4.9
             - libnetcdf-dev
       env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - ENVIRONMENT_LANGUAGE="c++"

     - os: linux
       language: cpp
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-5
             - libnetcdf-dev
       env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - ENVIRONMENT_LANGUAGE="c++"

     - os: linux
       language: cpp
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-6
             - libnetcdf-dev
       env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
         - ENVIRONMENT_LANGUAGE="c++"

     - os: linux
       language: cpp
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-7
             - libnetcdf-dev
       env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
         - ENVIRONMENT_LANGUAGE="c++"

     - os: linux
       language: cpp
       addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
             - libnetcdf-dev
             - g++-8
       env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
         - ENVIRONMENT_LANGUAGE="c++"

     - os: osx
       language: cpp
       env:
         - MATRIX_EVAL=""
         - ENVIRONMENT_LANGUAGE="c++"

     - os: osx
       language: cpp
       env:
         - MATRIX_EVAL=""
         - ENVIRONMENT_LANGUAGE="c++"
         - INSTALLFLAG="NETCDF"

     - os: linux
       language: r
       cache: Rcpp
       addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-4.9
       env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - ENVIRONMENT_LANGUAGE="r"

     - os: osx
       language: r
       cache: Rcpp
       env:
         - ENVIRONMENT_LANGUAGE="r"

before_install:
    - cmake --version
    - eval "${MATRIX_EVAL}"
    - if [[ "$ENVIRONMENT_LANGUAGE" == "c++" ]]; then if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall oclint; if [[ "$INSTALLFLAG" == "NETCDF" ]]; then brew install netcdf; fi; fi; fi
    - if [[ "$ENVIRONMENT_LANGUAGE" == "r" ]]; then R -e "install.packages('Rcpp')"; R -e "install.packages('BH')";fi
    - if [[ "$ENVIRONMENT_LANGUAGE" == "doc" ]]; then R -e "install.packages('Rcpp')"; R -e "install.packages('pkgdown')"; R -e "install.packages('BH')";fi

install:
    - if [[ "$ENVIRONMENT_LANGUAGE" == "r" ]]; then mkdir build-RAnEn; cd build-RAnEn; CC=$CC CXX=$CXX cmake -DINSTALL_RAnEn=On ..; fi

script:
    - if [[ "$ENVIRONMENT_LANGUAGE" == "c++" ]]; then mkdir build; cd build; CC=$CC CXX=$CXX cmake -DCMAKE_CXX_FLAGS="-coverage" -DCMAKE_BUILD_TESTS=ON ..; make -j16; fi
    - if [[ "$ENVIRONMENT_LANGUAGE" == "r" ]]; then make -j16; fi
    - if [[ "$ENVIRONMENT_LANGUAGE" == "doc" ]]; then ./deploymentAutomation/deploy.sh; fi

after_success:
    - if [[ "$ENVIRONMENT_LANGUAGE" == "c++" ]]; then make test; fi
    - if [[ "$ENVIRONMENT_LANGUAGE" == "r" ]]; then R -e "library(RAnEn)"; fi
    - bash <(curl -s https://codecov.io/bash)
