# Permalinks
permalink:           pretty

# Setup
title:               Parallel Ensemble Forecasts
tagline:             R and C++
url:                 https://weiming-hu.github.io/AnalogsEnsemble/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Weiming Hu
  url:               https://weiming.ddns.net
  email:             weiming@psu.edu

# Custom vars
version:             3.0.4
github:              https://github.com/Weiming-Hu
  repo:              https://github.com/Weiming-Hu/AnalogsEnsemble

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
