# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Parallel Ensemble Forecasts
tagline:          'R and C++'
description:      'An integrated package for parallel ensemble forecasts and more, implemented in R and C++.'
url:              https://weiming-hu.github.io/AnalogsEnsemble/
baseurl:          /

author:
  name:           'Weiming Hu'
  url:            https://weiming.ddns.net

paginate:         5
paginate_path:    "/posts/page:num/"

# Custom vars
version:          3.0
github:           
  repo:           https://github.com/Weiming-Hu/AnalogsEnsemble
