FROM ubuntu:18.04
LABEL maintainer="weiminghu@ucsd.edu"
LABEL description="A Linux Distribution of Parallel Analog Ensemble"

COPY . /AnalogEnsemble

RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    gcc g++ cmake libcppunit-dev doxygen graphviz \
    libnetcdf-c++4-dev libnetcdf-dev libeccodes-dev git wget \
    libboost-all-dev make r-base && rm -rf /var/lib/apt/lists/*
RUN DEBIAN_FRONTEND=noninteractive && apt-get autoremove && apt-get autoclean

WORKDIR /AnalogEnsemble/build_default
RUN cmake ..
RUN make install -j 8

RUN chmod -R 777 /AnalogEnsemble

