# "`-''-/").___..--''"`-._
#  (`6_ 6  )   `-.  (     ).`-.__.`)   WE ARE ...
#  (_Y_.)'  ._   )  `._ `. ``-..-'    PENN STATE!
#    _ ..`--'_..-_/  /--'_.' ,'
#  (il),-''  (li),'  ((!.-'
# 
# Author: Weiming Hu <weiming@psu.edu>
#         Geoinformatics and Earth Observation Laboratory (http://geolab.psu.edu)
#         Department of Geography and Institute for CyberScience
#         The Pennsylvania State University
#

#' RAnEn::generateAnalogs
#' 
#' RAnEn::generateAnalogs returns an AnEn class object. It usually includes the 
#' member `analogs` and other members as specified in the configuration.
#' 
#' The return value is an AnEn list.
#' 
#' The list member **analogs** is a 5-dimensional array that contains values
#' and indices of ensemble members from the observations. The dimensions are 
#' **analogs\[test stations, test days, FLT, members, ...\]**
#' where FLT stands for forecast lead time. The size of the fifth dimension
#' is 3, storing the value \[,,,,1\], station index \[,,,,2\], and observation
#' time index \[,,,,3\]. Negative observation time indices are typically associated with
#' NA ensemble members and these negative values show the reason why a
#' particular member has an NA value. Please refer to
#' [AnEn::selectAnalogs](https://weiming-hu.github.io/AnalogsEnsemble/CXX/class_an_en.html#a8e2b88cda5cc9fce8ea4703a3236719c).
#' 
#' The list member **similarity** stores the similarity metrics.
#' The dimension indication is the same with the member **analogs**.
#' The size of the fifth dimension is 3, storing the similarity value
#' \[,,,,1\], station index \[,,,,2\], and forecast time index \[,,,,3\].
#' Negative forecast time indices are typically associated with NA 
#' similarity values and these nagetive values show the reason why a particular
#' similarity value is NA. Please refer to 
#' [AnEn::computeSimilarity](https://weiming-hu.github.io/AnalogsEnsemble/CXX/class_an_en.html#a787e43e7bfdaa830bf70fa6710731614).
#' 
#' The list member **searchStations** stores the search station index.
#' 
#' The list member **mapping** stores the lookup table mapping from 
#' forecast times and flts to observation times. This table can alos be generated
#' using \code{\link{generateTimeMapping}}.
#' 
#' @author Weiming Hu \email{weiming@@psu.edu}
#' 
#' @param configuration A configuration object generated by the function
#' \code{\link{generateConfiguration}}.
#' 
#' @return An AnEn list with customized members. Please check details in the 
#' detail secion.
#' 
#' @import Rcpp BH
#' 
#' @useDynLib RAnEn
#' 
#' @md
#' @export
generateAnalogs <- function(configuration) {
  
  configuration <- formatConfiguration(configuration, configuration$verbose > 2)
  valid <- validateConfiguration(configuration)
  if (!valid) return(valid)
  
  configuration <- convertToAdvance(configuration)
  
  configuration$observation_id = configuration$observation_id - 1
  
  # Call the C++ routine
  AnEn <- .generateAnalogs(configuration)
  
  # Because similarity matrix was stored in row-major in C++ and the R object will be column-major.
  # So change the order of dimensions to make it conform with other objects.
  #
  if (configuration$preserve_similarity) {
    AnEn <- AnEnC2R(AnEn, 'similarity')
  }

  if (configuration$preserve_search_stations) {
    AnEn$searchStations <- AnEn$searchStations + 1
  }

  AnEn <- AnEnC2R(AnEn, 'analogs')

  if (configuration$preserve_mapping) AnEn$mapping <- AnEn$mapping + 1

  if (configuration$verbose >= 3)  cat("Done (generateAnalogs)!\n")
  
  return(AnEn)
}
