# Reference: https://github.com/r-lib/actions/tree/master/examples

name: Build R

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        
      - name: Install R dependencies
        run: install.packages(c('Rcpp', 'BH'))
        shell: Rscript {0}
      
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
      
      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake -DINSTALL_RAnEn=ON ..
      
      - name: Build and Install
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: make && make install
      
      - name: Test
        working-directory: ${{github.workspace}}/RAnalogs/tests
        run: Rscript test_all.R
