# Reference: https://github.com/r-lib/actions/tree/master/examples

name: Build R

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        
      - name: Install dependencies
        run: |
          Sys.unsetenv("PKG_CXXFLAGS")
          install.packages(c('Rcpp', 'BH'))
          install.packages("https://github.com/Weiming-Hu/AnalogsEnsemble/raw/master/RAnalogs/releases/RAnEn_latest.tar.gz", repos = NULL)
        shell: Rscript {0}
      
      - name: Check
        working-directory: ${{github.workspace}}/RAnalogs/tests
        run: Rscript test_all.R
